### ISSUE TITLE
Key all commands on pipeline

### ISSUE THREAD

**Issue by appleton** [heroku/heroku-ci#10]
All commands currently only accept an app as the base, from which we look up the pipeline. This is a little odd since CI belongs to a pipeline.

We should allow all commands to accept a `-p` flag to specify the pipeline directly, but continue to support app lookup.

**Comment by gulopine** [comment]
It seems most of the commands have been given a `-p, --pipeline` option, but `heroku ci` still notably still requires an app name.

**Comment by raulb** [comment]
@gulopine thanks for noticing! This was was a miss from https://github.com/heroku/heroku-ci/pull/33.

Just opened this one: https://github.com/heroku/heroku-ci/pull/56.

**Comment by raulb** [comment]
@gulopine this will be available the next time we cut a new release of `heroku ci` and [`Heroku CLI`](https://github.com/heroku/cli/blob/master/package.json#L44).

Documented at:
https://github.com/heroku/heroku-ci/blob/master/CHANGELOG.md#unreleased

Thanks again for noticing!
