### ISSUE TITLE
Error running watch

### ISSUE THREAD

**Issue by maxbeizer** [heroku/heroku-ci#19]
```
$h --version
heroku-cli/5.6.26-e6aeac4 (darwin-amd64) go1.7.5

$h plugins
heroku-ci 1.3.0

$h ci --watch -r staging
=== Watching latest test runs for the blog pipeline
 ▸    cli.color[STATUS_COLORS[status]] is not a function
```

If it helps, I cancelled a build and restarted it before this happened.

**Comment by appleton** [comment]
We've added some new states, `debugging` and `cancelled` since this code was written. I think I need to make that block a little more defensive!

Thanks for the feedback, I'll whip up a fix now.

**Comment by appleton** [comment]
I just published a fix to npm as v1.3.1

**Comment by maxbeizer** [comment]
Thanks @appleton !

**Comment by raulb** [comment]
Thanks @maxbeizer for reporting 👊
