### ISSUE TITLE
Heroku Generated Env vars not present on `ci:debug`

### ISSUE THREAD

**Issue by schneems** [heroku/heroku-ci#41]
Test runs on `ci:debug` do not get the same environment variables set as test runs from a pipeline. This means if you have code that depends on one of these env vars you will get different behavior in test and in `ci:debug`

- HEROKU_TEST_RUN_BRANCH
- HEROKU_TEST_RUN_ID
- HEROKU_ENV

We should either include these in `ci:debug` or add an extra environment variable such as `HEROKU_IS_RUNNING_CI` and document it.

**Comment by appleton** [comment]
I've shipped a new version which includes `HEROKU_TEST_RUN_BRANCH`, `HEROKU_TEST_RUN_ID`, `CI_NODE_INDEX` and `CI_NODE_TOTAL` but `HEROKU_ENV` is supposed to be in internal thing so I've kept it out and opened a PR internally to remove it from the test run environment.

This is already on npm `heroku-ci@1.8.0` and will be in the mainline CLI once https://github.com/heroku/cli/pull/483 is shipped.

**Comment by schneems** [comment]
Awesome, thanks!

Can we document an officially sanctioned env var that people can use to know when they're running on CI?

**Comment by appleton** [comment]
Yes,`HEROKU_TEST_RUN_ID` is the one. We'll get it documented.

**Comment by jmorrell** [comment]
This should be `CI=true` to mimic other CI providers: https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
