### ISSUE TITLE
Reporting to external coverage tools requires additional git info

### ISSUE THREAD

**Issue by jwmayfield** [heroku/heroku-ci#59]
All of the tools I've checked (Codacy, Code Climate, and Codecov) require at least the SHA for the commit under test, in addition to the branch name (which we have access to as an environment variables).  Code Climate at least also requires a value for "committed at", which is the result of `git log -1 --pretty=format:'%ct'`.

Any possibility of getting these added into the environment of a CI run?

**Comment by joshwlewis** [comment]
Hi @jwmayfield -- I just shipped a change that includes `HEROKU_TEST_RUN_COMMIT_VERSION` as an environment variable for each test run. I'll be updating the docs soon.

Adding the commit timestamp is a little more challenging, as we aren't collecting that information when the test run starts. We have some plans that may enable that in the future, but I really can't promise a timeline.

Thanks for reaching out.

**Comment by Deekor** [comment]
Any update on this? Was going to switch from Travis CI but I guess I cant until this is supported...
