### ISSUE TITLE
Enable Heroku CI through the Heroku API

### ISSUE THREAD

**Issue by NickLiffen** [heroku/heroku-ci#63]
Currently, there is no way to enable Heroku CI on a pipeline via the Heroku API.

Heroku's GUI sits ontop of the Heroku API(s), which means there must be an API beheind the scenes making the call (just a private one not documented or exposed).

Is there any chance we could please expose an API endpoint to enable Heroku CI on the pipeline? I currently see no docuentation on your public API.

**Comment by appleton** [comment]
You're right that there is no way today. Our team is working on a project to expose a number of CI and pipelines related endpoints over the next few months so I'l make sure that this is on our radar.

In the interim you could try checking the web inspector for the endpoints we hit when enabling CI from dashboard but be aware that if you start using the same endpoint it will likely change soon without warning!
